apiVersion: v1
kind: BuildConfig
metadata:
  name: gandhicloudlab.dev-gan2-012-test1
  labels:
    app: dev-gan2-012-test1
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/GandhiCloudLab/dev-gan2-012-test1.git'
      ref: master
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-gan2
        - name: BRANCH
          value: master
